[package]
name = "aoc2025"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
fs-err = "3.2.0"
indicatif = { version = "0.18.3", features = ["improved_unicode", "rayon"] }
itertools = "0.14.0"
rayon = "1.11.0"
